import { z } from "zod";

import sheetJson from "../../../public/companion/bear/bear-sprites.json";

/**
 * The bear's sprite sheet, generated by assets/companion/bear/generate_bear_sprites.py:
 * one row per animation, frames left to right, each with its own duration.
 */
export const bearAnimations = [
  "idle",
  "sit_down",
  "read",
  "map_down",
  "eat",
  "map_up",
  "stand_up",
  "cheer",
  "worried",
] as const;

export type BearAnimation = (typeof bearAnimations)[number];

const animationSchema = z
  .object({
    row: z.number().int().min(0),
    frames: z.number().int().positive(),
    durationsMs: z.array(z.number().positive()),
  })
  .refine((animation) => animation.durationsMs.length === animation.frames, {
    message: "Every frame needs exactly one duration.",
  });

const sheetSchema = z.object({
  frameWidth: z.number().int().positive(),
  frameHeight: z.number().int().positive(),
  animations: z.record(z.enum(bearAnimations), animationSchema),
});

export type BearSpriteSheet = z.infer<typeof sheetSchema> & {
  readonly url: string;
  readonly columns: number;
  readonly rows: number;
};

/** Parses the generated frame list, so a regenerated sheet missing an animation fails loudly. */
export function parseBearSpriteSheet(value: unknown): BearSpriteSheet {
  const sheet = sheetSchema.parse(value);
  const animations = Object.values(sheet.animations);
  return {
    ...sheet,
    url: "/companion/bear/bear-sprites.png",
    columns: Math.max(...animations.map((animation) => animation.frames)),
    rows: Math.max(...animations.map((animation) => animation.row)) + 1,
  };
}

export const bearSpriteSheet = parseBearSpriteSheet(sheetJson);
